/**
 * Orval Configuration
 *
 * Generates TypeScript types and API clients from OpenAPI specification
 * Run: pnpm generate:api-types-orval
 */

const generateTypesOutput = './src/lib/api/generated'

module.exports = {
  blogApi: {
    input: './openapi.json',
    output: {
      mode: 'single',
      target: `${generateTypesOutput}/types.ts`,
      schemas: `${generateTypesOutput}/schemas`,
      CleanNamespace: true,
    },
    hooks: {
      afterAllFilesWrite: ['pnpm prettier --write'],
    },
    config: {
      version: '8.0.4',
      header: ['Generated by Orval', 'DO NOT EDIT'],
    },
  },
}
