// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blog']['schema']['_output']
export declare const blog: Blog[]

export type Authors = Collections['authors']['schema']['_output']
export declare const authors: Authors[]
