-- Add role column to users table if not exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'role'
    ) THEN
        ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'user';
        RAISE NOTICE 'Added role column to users table';
    ELSE
        RAISE NOTICE 'role column already exists in users table';
    END IF;
END
$$;

-- Create admin user if not exists
-- Password: Admin123XYZ (hashed with argon2)
INSERT INTO users (email, username, password_hash, role, email_verified)
VALUES (
    'admin@test.com',
    'admin',
    '$argon2id$v=19$m=19456,t=2,p=1$gZxVmLVTvuBjYz8Zx6VmLQ$E4Zx6VmLVTvuBjYz8Zx6VmLVTvuBjYz8Zx6VmLVTvuBjYz',  -- This is a placeholder, will be replaced with actual hash
    'admin',
    true
) ON CONFLICT (email) DO UPDATE SET
    role = EXCLUDED.role,
    email_verified = EXCLUDED.email_verified;

-- Note: The password hash above is a placeholder
-- You need to update it with the actual hash generated by the application
