apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - api-service.yaml
  - frontend-service.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - migrate-job.yaml
  - api-hpa.yaml
  - frontend-hpa.yaml
  - api-pdb.yaml
  - frontend-pdb.yaml
  - ingress.yaml
images:
  - name: blog-backend
    newName: ghcr.io/zhengbi-yong/zhengbi-yong.github.io/blog-backend
    newTag: 1.8.2
  - name: blog-frontend
    newName: ghcr.io/zhengbi-yong/zhengbi-yong.github.io/blog-frontend
    newTag: 1.8.2
