/**
 * Contentlayer compatibility shim
 *
 * This module provides shimmed exports that mimic the contentlayer API,
 * but uses data generated by Velite instead.
 *
 * Velite generates JSON files in .velite/ directory during build.
 */

import blogData from '../../../.velite/blog.json' with { type: 'json' }
import authorData from '../../../.velite/authors.json' with { type: 'json' }

// Slugify function to match Velite's behavior
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export interface Blog {
  _id: string
  _raw: { sourceFilePath: string }
  title: string
  date: string
  tags?: string[]
  category?: string
  lastmod?: string
  draft?: boolean
  summary?: string
  images?: string[]
  authors?: string[]
  layout?: string
  showTOC?: boolean
  author?: string
  description?: string
  content: string
  slug: string
  path: string
  filePath: string
  readingTime: string
  body: { code: string }
}

type VeliteBlogPost = {
  title: string
  date: string
  tags?: string[]
  category?: string
  lastmod?: string
  draft?: boolean
  summary?: string
  author?: string
  authors?: string[]
  layout?: string
  showTOC?: boolean
  description?: string
  content?: string
  categories?: string[]
  math?: boolean
  [key: string]: unknown
}

function estimateReadingTime(content: string): string {
  const wordsPerMinute = 200
  const textLength = content.replace(/<[^>]*>/g, '').length
  const minutes = Math.ceil(textLength / wordsPerMinute)
  return `${minutes} min read`
}

function transformVeliteBlog(post: VeliteBlogPost): Blog {
  const computedSlug = slugify(post.title)
  const computedPath = `blog/${computedSlug}`
  const computedFilePath = `${computedPath}.mdx`

  return {
    _id: computedSlug,
    _raw: { sourceFilePath: computedFilePath },
    title: post.title,
    date: post.date,
    tags: post.tags,
    category: post.category,
    lastmod: post.lastmod,
    draft: post.draft,
    summary: post.summary || post.description,
    images: undefined,
    authors: post.authors,
    layout: post.layout,
    showTOC: post.showTOC,
    author: post.author,
    description: post.description,
    content: post.content || '',
    slug: computedSlug,
    path: computedPath,
    filePath: computedFilePath,
    readingTime: estimateReadingTime(post.content || ''),
    body: { code: post.content || '' },
  }
}

export const allBlogs: Blog[] = blogData.map(transformVeliteBlog)

export interface Author {
  _id: string
  _raw: { sourceFilePath: string }
  name: string
  avatar?: string
  occupation?: string
  company?: string
  email?: string
  twitter?: string
  bluesky?: string
  linkedin?: string
  github?: string
  layout?: string
  content: string
  slug: string
  body: { code: string }
}

type VeliteAuthor = {
  name: string
  avatar?: string
  occupation?: string
  company?: string
  email?: string
  twitter?: string
  linkedin?: string
  github?: string
  content?: string
  [key: string]: unknown
}

function transformVeliteAuthor(post: VeliteAuthor): Author {
  const computedSlug = post.name

  return {
    _id: computedSlug,
    _raw: { sourceFilePath: `authors/${computedSlug}.mdx` },
    name: post.name,
    avatar: post.avatar,
    occupation: post.occupation,
    company: post.company,
    email: post.email,
    twitter: post.twitter,
    bluesky: undefined,
    linkedin: post.linkedin,
    github: post.github,
    layout: undefined,
    content: post.content || '',
    slug: computedSlug,
    body: { code: post.content || '' },
  }
}

export const allAuthors: Author[] = (authorData || []).map(transformVeliteAuthor)

export type { Author as Authors }
